apiVersion: v1
kind: Service
metadata:
  name: iperf-server-nodeport
spec:
  selector:
    app: iperf-server
  ports:
  - name: iperf
    port: 5001
    protocol: UDP
    targetPort: 5001
  type: NodePort

