apiVersion: v1
kind: Service
metadata:
  name: iperf-server-loadbalancer
spec:
  selector:
    app: iperf-server
  ports:
  - name: 5001-udp
    protocol: UDP
    port: 5001
    targetPort: 5001
  type: LoadBalancer
